---
title: "eda"
format: html
editor: visual
---

# How many cases

pending cases are codded as tapeyear == 2099 for some reason.

```{r}

library(DBI)
library(tidyverse)
source("lookups.R")

ds <- arrow::open_dataset("data")

ds |> 
  group_by(TAPEYEAR) |> 
  tally() |> 
  collect() -> temp

temp |> 
  filter(TAPEYEAR != 2099) |> 
  arrange(TAPEYEAR) |> plot()

```

Disposition time series

```{r}

monthly_disposition <- ds |> 
  arrow::to_duckdb() |> 
  mutate(closed_month = lubridate::floor_date(TERMDATE, "month")) |> 
  group_by(closed_month, DISP) |> 
  tally() |> 
  collect()

monthly_disposition |> 
  filter(DISP != -8) |> 
  filter(closed_month >= lubridate::ymd("1988-01-01")) |> 
  left_join(disp) |> 
  ggplot(aes(closed_month, n, group = type, color = as.factor(type))) +
  geom_line() 
  


```

```{r}

monthly_juris <- ds |> 
  arrow::to_duckdb() |> 
  mutate(closed_month = lubridate::floor_date(TERMDATE, "month")) |> 
  group_by(closed_month, JURIS) |> 
  tally() |> 
  collect()

monthly_juris |> 
  filter(JURIS == 1) |> 
  filter(closed_month >= lubridate::ymd("1988-01-01")) |> 
  ggplot(aes(closed_month, n)) +
  geom_line() + 
  labs(
    x = "Date closed"
    , y = "Total Federal Suits"
    , title = "Federal lawsuits with US government Plaintiff")


```

```{r}

ds |> 
  filter(JURIS == 1) |> 
  filter(TAPEYEAR != 2099) |> 
  filter(TITL == 28) |> 
  group_by(TAPEYEAR, SECTION) |> 
  tally() |> 
  collect() |> 
  ggplot(aes(TAPEYEAR, n, color = SECTION)) +
  geom_line()


```

how long was a case open when it closed

```{r}

ds |> 
  head(1000) |> 
  pull(FILEDATE) 

ds |> 
  arrow::to_duckdb() |> 
  filter(DISP != -8) |> 
  mutate(
    days_to_resolve =  TERMDATE - FILEDATE
    , month = lubridate::floor_date(TERMDATE, "year")) |>
  group_by(month) |> 
  summarise(days = mean(days_to_resolve)) |> 
  collect() -> days_ts
      
days_ts |> 
  filter(month >= lubridate::ymd("1988-01-01")) |> 
  ggplot(aes(month, days)) +
  geom_line()

ds |> 
  filter(DISP == -8
         , JURIS != 4) |> 
  arrow::to_duckdb() |> 
  mutate(month = lubridate::floor_date(FILEDATE, "month")) |> 
  group_by(month, JURIS) |> 
  tally() |> 
  ggplot(aes(month, n, color = as.factor(JURIS))) + 
  geom_line()

```

so I think we want to model the time to closure with a censored model.

let's pick a type of jurisdiction (federal question) and a couple of circuits (5th and 11th) over the last 7 years.

```{r}

table_df <- function(df, column){
  df |> 
    group_by({{column}}) |> 
    tally() |> 
    collect()
}



```
